// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYkmnZVDZsATGVcqYhVpYcpwaupesRuQk',
    appId: '1:863809569752:web:539ecfdd71aa6f3e75a8ad',
    messagingSenderId: '863809569752',
    projectId: 'baby-store-app-388a4',
    authDomain: 'baby-store-app-388a4.firebaseapp.com',
    storageBucket: 'baby-store-app-388a4.firebasestorage.app',
    measurementId: 'G-VNZMPQR7NC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb93dMW-q8tFVlAkTn-UA3t3Au9iYkdGc',
    appId: '1:863809569752:android:8f58fb6c38b54af375a8ad',
    messagingSenderId: '863809569752',
    projectId: 'baby-store-app-388a4',
    storageBucket: 'baby-store-app-388a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwlyPTwpHcA56y3VmMk3Zv1lJ6RLYr03I',
    appId: '1:863809569752:ios:d68eda3dd8e7b80b75a8ad',
    messagingSenderId: '863809569752',
    projectId: 'baby-store-app-388a4',
    storageBucket: 'baby-store-app-388a4.firebasestorage.app',
    iosBundleId: 'com.example.babyStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwlyPTwpHcA56y3VmMk3Zv1lJ6RLYr03I',
    appId: '1:863809569752:ios:d68eda3dd8e7b80b75a8ad',
    messagingSenderId: '863809569752',
    projectId: 'baby-store-app-388a4',
    storageBucket: 'baby-store-app-388a4.firebasestorage.app',
    iosBundleId: 'com.example.babyStoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYkmnZVDZsATGVcqYhVpYcpwaupesRuQk',
    appId: '1:863809569752:web:c880eb2a49812a7775a8ad',
    messagingSenderId: '863809569752',
    projectId: 'baby-store-app-388a4',
    authDomain: 'baby-store-app-388a4.firebaseapp.com',
    storageBucket: 'baby-store-app-388a4.firebasestorage.app',
    measurementId: 'G-DP43CMD73L',
  );
}
